# Generated by Django 2.2.7 on 2022-03-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191207_1031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug',)},
        ),
    ]
