# Generated by Django 2.2.7 on 2022-03-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'pages'), ('model', 'pages')), models.Q(('app_label', 'blog'), ('model', 'post')), models.Q(('app_label', 'blog'), ('model', 'category')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Ссылка на'),
        ),
    ]
